version: '3'
services:
  backend:
    image: ismailcharfi/tp4-backend:latest
    container_name: tp4-backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    depends_on:
      - mongodb
    environment:
      PORT: 6060
      DB_URL: mongodb://mongodb:27017/todo
  frontend:
    container_name: tp4-frontend
    image: ismailcharfi/tp4-frontend:latest
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      PORT: 7070
      API_PATH: "http://localhost:6060"
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
