version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: back-end/Dockerfile
    ports:
      - "6060:6060"
    depends_on:
      - mongodb
    environment:
      PORT: 6060
      DB_URL: mongodb://mongodb:27017/todo
  frontend:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    ports:
      - "7070:7070"
    environment:
      PORT: 7070
      API_PATH: "http://localhost:6060"
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
